### ISSUE TITLE
<class 'UnicodeDecodeError'> 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by wupco** [matrix1001/heapinspect#3]
`/proc/*/maps` are not `utf-8` encoded files

https://github.com/matrix1001/heapinspect/blob/master/heapinspect/proc.py#L23
https://github.com/matrix1001/heapinspect/blob/master/heapinspect/proc.py#L104
https://github.com/matrix1001/heapinspect/blob/master/heapinspect/proc.py#L295

```
217gdb> hi tcache
Python Exception <class 'UnicodeDecodeError'> 'utf-8' codec can't decode byte 0xb8 in position 40: invalid start byte: 
Error occurred in Python command: 'utf-8' codec can't decode byte 0xb8 in position 40: invalid start byte
```
```
➜  ~ locale  
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

```

**Comment by wupco** [comment]
Perhaps you should use `'rb' `.

**Comment by V1NKe** [comment]
2333我是报了0xb0的错误，修改'rb'后又报错：
`Python Exception <class 'TypeError'> ord() expected string of length 1, but int found:`

**Comment by matrix1001** [comment]
有没有具体错误信息？比如哪一行有问题。

**Comment by matrix1001** [comment]
尝试在错误发生时，使用另一个命令行运行`python HeapInspect.py pid`，`pid`填成和gdb里面的一样，然后看看能不能正常运行，如果有报错，麻烦发一下。 @wupco @V1NKe

**Comment by matrix1001** [comment]
这个问题看起来是gdb python3的问题，由于对于二进制文件我都是使用`open(file).read()`的方式，导致了这个错误，后面会想想怎么修复。

**Comment by V1NKe** [comment]
@matrix1001 单运行`python HeapInspect.py pid`不会有错误，正常，应该是gdb python3的问题。

**Comment by matrix1001** [comment]
@wupco @V1NKe 刚刚更新了，现在支持python3了，gdb也是支持的，有空试一试，有问题我再修
