### ISSUE TITLE
Does this work for other allocators?

### ISSUE THREAD

**Issue by Albocoder** [matrix1001/heapinspect#8]
It seems that glibc is being referred in the README file. Does this mean that the library only works for ptmalloc2?
I believe a heap-diff doesn't need any priors, but the size, next, prev etc are very related to the allocator.

**Comment by matrix1001** [comment]
@Albocoder Only works for ptmalloc2. Heap-diff and other features are not fully implemented yet (lazy me).

**Comment by Albocoder** [comment]
Thank you! I will take a look if I can implement the diff. I'm curious what your idea for the heap diff is (if it's what I had in mind). Can you please elaborate? Maybe in this thread or just a Twitter DM.
